version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"          
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
    open-pull-requests-limit: 5
    target-branch: "dev"
    groups:
      # Name the group (this will appear in the PR title)
      all-minor-and-patch-updates:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "dev"
